"""check_db_model_consistency_post_roll_number_refactor

Revision ID: 09111cf906d2
Revises: 9f4714ac8efc
Create Date: 2025-05-21 13:23:13.063430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09111cf906d2'
down_revision: Union[str, None] = '9f4714ac8efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
