"""add_roll_number_to_users

Revision ID: 9f4714ac8efc
Revises: 0dfb1801960a
Create Date: 2025-05-21 11:57:30.392760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4714ac8efc'
down_revision: Union[str, None] = '0dfb1801960a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_number', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_roll_number'), ['roll_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_roll_number'))
        batch_op.drop_column('roll_number')

    # ### end Alembic commands ###
